---
title: "Appendix"
author: "Sina Furkan Özdemir"
date: "10/5/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F,message = F)
library(pacman)
packs<- c("tidyverse","here","gtsummary")
p_load(char = packs,install = T)
data_path<- here("Data")
graph_path<- here("Graphs")
eu_assoc<- c("(Stabilisation and) Association agreement","Candidacy (for membership)","Customs Union","Europe - Belonging","European Union","Schengen Area")

data = readRDS(file = file.path(data_path,"replication_data_w_frames.RDS")) %>% filter(i_organization_string %in% eu_assoc)

```



# Appendix:

## Full descriptive statistics of the data:


```{r desc_stats}
desc_stat_org<- data %>% select(a_party_string,i_organization_string,i_position_string)
parties<- unique(as.character(desc_stat_org$a_party_string))

c_tabs<-list()

for(i in 1:length(parties)){
  ctab<- desc_stat_org %>% 
    filter(a_party_string == parties[i]) %>% 
    tbl_cross(data = .,
              row = i_organization_string,
              col = i_position_string,
              percent = "cell",
              label = i_organization_string~"Debated organization") %>% 
    modify_header(label ~"")
    
   c_tabs[[i]]<-ctab
}

tbl_merge(c_tabs,tab_spanner = parties)


```


## Cross-tabulation of frames by party on EU membership

```{r frame_desc_stats_a}
eu_assoc<- c("(Stabilisation and) Association agreement","Candidacy (for membership)","Customs Union","Europe - Belonging","European Union","Schengen Area")

frame_desc<-data %>% filter(i_organization_string %in% eu_assoc) %>% select(a_party_string,i_organization_string,i_position_string,cost_benefit:fairnes) %>% pivot_longer(.,cols = cost_benefit:fairnes,names_to = "frame") %>% filter(value == 1) %>% select(-value) %>% mutate(across(everything(),~as.character(.)))

parties<- unique(as.character(frame_desc$a_party_string))

c_tabs<-list()

for(i in 1:length(parties)){
  ctab<- frame_desc %>% 
    filter(a_party_string == parties[i]) %>% 
    tbl_cross(data = .,
              row = frame,
              col = i_position_string,
              percent = "cell",
              label = frame~"Frames for EU membership") %>% 
    modify_header(label ~"")
    
   c_tabs[[i]]<-ctab
}

tbl_merge(c_tabs,tab_spanner = parties)


```

